### ISSUE TITLE
Unable to log into account

### ISSUE THREAD

**Issue by binloan** [lorenzo-deluca/homeassistant-silence#1]
When using your python file independently I can not connect to my account getting the following error:

`{'error': {'code': 400, 'message': 'EMAIL_NOT_FOUND', 'errors': [{'message': 'EMAIL_NOT_FOUND', 'domain': 'global', 'reason': 'invalid'}]}}`

How do I have to input username / password corrently? Is it plaintext?

**Comment by lorenzo-deluca** [comment]
Hello, you have to enter email address and password in the configuration yaml file, as for all credentials you can keep them in the secret.yaml file ;)

**Comment by binloan** [comment]
@lorenzo-deluca thanks. If I don't use homeassistant but execute your module directly via Python 3.6 how do I have to supply your API with username and password? I guess that was my initial question.
