### ISSUE TITLE
Remote controls from the app, such as on/off, opening the under seat and alarm activation, are still to be managed

### ISSUE THREAD

**Issue by barnynv** [lorenzo-deluca/homeassistant-silence#13]
Hello, I see that the improvements of this great project have stopped. I don't know what the problem is, do you plan to resume the improvements for remote start, opening the seat and activating the alarm?

A greetings

**Comment by lorenzo-deluca** [comment]
Hello, now I'm working on this project [silence-private-server](https://github.com/lorenzo-deluca/silence-private-server).
It's a self-hosted server for Silence and Seat Astra module, it's already support all command.
