### ISSUE TITLE
error retreiving token

### ISSUE THREAD

**Issue by luggi** [lorenzo-deluca/homeassistant-silence#2]
Thanks for this integration, unfortunately it does not work for me and fails with the following message:
[custom_components.silencescooter.sensor] token json_response={'error': {'code': 400, 'message': 'EMAIL_NOT_FOUND', 'errors': [{'message': 'EMAIL_NOT_FOUND', 'domain': 'global', 'reason': 'invalid'}]}}
[custom_components.silencescooter.sensor] Could not retrieve token (unknown).
[homeassistant.components.sensor] silencescooter: Error on device update!
Any ideas what i could try ?
The credentials are definitely correct.
Thanks,
Lukas

**Comment by lucasimons** [comment]
Do you have a silence or a seat ? because i have the same problem with seat Mò

**Comment by lorenzo-deluca** [comment]
Hello, I've **Silence Scooter**
So the problem is due to the fact that the APIs called by the Seat app will surely be different.

If any of you know about proxies could "sniff" the API that the Seat app calls and I could implement it.
Or you can implement it yourself and make a pull request ;)

**Comment by luggi** [comment]
It's a Silence S01 Connected, maybe there was some change with the newer models.

**Comment by flixlix** [comment]
> If any of you know about proxies could "sniff" the API that the Seat app calls and I could implement it. Or you can implement it yourself and make a pull request ;)

Hey, I have a Seat Mó and have some free time to implement this. Can you give me some info on what software you used? / How you reverse engineered the API?

**Comment by luggi** [comment]
So I got around to fix this.. So with this I guess you can actually close the issue ;)
As it turns out for whatever reason the google api key is different for me.

The API-key can be found extracting the MySilence APK via "Apk Extractor" and then using http://www.javadecompilers.com for extracting the source. The API key can then be found in \resources\res\values\strings.xml under the key google_api_key.

**Comment by lorenzo-deluca** [comment]
Good to know @luggi ... I take the API-Key from my iOS Silence App.. and it works for many users.. strange that it doesn't work for you,
Anyway, I'm working on new version of this integration which adds gps tracking and some remote control functionality, do you think it might be useful to add the api-key as an optional configuration parameter?

**Comment by luggi** [comment]
Yeah having it as an extra configuration parameter would be great!
So far just changing the api-key seems to work well for me.
